language: node_js
node_js: '9'

os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

script:
- npm run lint
- electron-forge publish --target github