language: node_js
node_js:
  - '9'

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    addons:
      apt:
        packages:
        - fakeroot
        - rpm
  - os: osx
sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
notifications:
  email: false
script:
  - npm run publish

deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true